version: '3'
services:
    database:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        volumes:
            - database:/var/lib/mysql
        environment:
            MYSQL_DATABASE: tchather
            MYSQL_ROOT_PASSWORD: tUs2sdxGrHJmi79jTGd4wFEPRPUT9uHBR3dnMBkJh
volumes:
    database:
